" filetype plugin on
" filetype indent on

set nocompatible " This must be first, because it changes other options as a side effect.

let mapleader = ","   " Sets leader key to ','

"General setting
syntax enable
set background=dark
set t_Co=256
set clipboard=unnamed     " Use the same clipboard as system clipboard
set linebreak
set term=screen-256color  "Adds colorsupport inside tmux
set mouse=a               " Enable the mouse in vim.
set wildmenu              " Much nicer tab completion for commands
set scrolloff=5           " Keep 5 lines below and above the cursor 
set autoread              " Reload files changed outside vim
set novisualbell          " No sounds
set noswapfile            " No swap files
set nobackup              " No swap files
set nowb                  " No swap files
set nowrap                " No line wrapping

nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

"Spaces and tabs
set tabstop=2         " 2 space tab
set shiftwidth=2
set softtabstop=2     " 2 space tab
set expandtab         " use spaces for tabs
set smarttab          " insert tabstop number of spaces when the tab key is pressed

"UI Layout
set number          " show line numbers
set showcmd         " show command in bottom bar
set nocursorline    " highlight current line
set lazyredraw      " Don't update screen during macro and script execution.

"Folding
set nofoldenable        " Disable folding by default

"Searching
set ignorecase      " ignore case when searching
set incsearch       " search as characters are entered
set hlsearch        " highlight all matches
set ignorecase        " Searching is not case sensitive

"Disable arrow keys and break the bad habbit :'(
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

"Move normally between wrapped lines
nmap j gj
nmap k gk

"Vim spell
set spellfile=$HOME/.vim-spell-en.utf-8.add " This will be a symlink to the dotfiles version of the spellfile
autocmd FileType markdown setlocal spell    " Spell check markdown
autocmd FileType gitcommit setlocal spell   " Spell check git commit messages
set complete+=kspell                        " For filetypes with spellcheck available, we'll also support auto-complete.

" Don't count acronyms / abbreviations as spelling errors
" (all upper-case letters, at least three characters)
" Also will not count acronym with 's' at the end a spelling error
" Also will not count numbers that are part of this
" Recognizes the following as correct:
au BufNewFile,BufRead syn match AcronymNoSpell '\<\(\u\|\d\)\{3,}s\?\>' contains=@NoSpell
au BufNewFile,BufRead syn match UrlNoSpell '\w\+:\/\/[^[:space:]]\+' contains=@NoSpell


" Install vim-plug if not found.
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Run PlugInstall if there are missing plugins.
autocmd VimEnter * if len(filter(values(g:plugs),'!isdirectory(v:val.dir)'))
  \| PlugInstall --sync | source $MYVIMRC
\| endif

call plug#begin('~/.vim/plugged')

"General
Plug 'nathanaelkane/vim-indent-guides'  " Shows indents
Plug 'ntpeters/vim-better-whitespace'   " Highlight whitespaces

"Theme
Plug 'bling/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'dracula/vim',{'as':'dracula'}

call plug#end()

"Vim-airline theme
let g:airline_theme = 'minimalist'

"Vim-better-whitespace
let g:better_whitespace_enabled=1
let g:better_whitespace_ctermcolor='lightmagenta'
let g:better_whitespace_guicolor='lightmagenta'
let g:show_spaces_that_precede_tabs=1               " Highlight spaces that appear before or in-between tabs

"Vim-indent-guides
let g:indent_guides_guide_size = 1                  " Size of indent
let g:indent_guides_start_level = 2                 " Starts showing from second level
let g:indent_guides_enable_on_vim_startup = 1       " Enable indent guides on startup

"Vim-auto-save
let g:auto_save=1 " Enable AutoSave on startup

"Language specific configuration.
au FileType make      set noexpandtab shiftwidth=8 softtabstop=0 " Makefiles must use tabs
au FileType yaml      setl  sw=2 sts=2
au FileType json      syntax match Comment +\/\/.\+$+

colorscheme dracula
