bindkey -a u undo
bindkey -a '^R' redo
bindkey '^?' backward-delete-char

export LANGUAGE=en_US.UTF-8           # fixes perl locale errors
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_TYPE=en_US.UTF-8

# ZSH | oh-myzsh settings
ZSH_THEME="theunraveler"                                # ZSH theme - See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
CASE_SENSITIVE="false"                                  # Case sensitive completion 
HYPHEN_INSENSITIVE="true"                               # while completing '_' and '-' will be interchangeable
COMPLETION_WAITING_DOTS="true"                          # Red dots whilst waiting for completion.
DISABLE_UNTRACKED_FILES_DIRTY="true"                    # disable marking untracked files (great for large repos)

###################
###   PLUGINS   ###
###################

source ~/.zplug/init.zsh                                # initialize plugins 
zplug "plugins/ssh-agent", from:oh-my-zsh               # Automatically starts the ssh agent
zplug "plugins/autojump", from:oh-my-zsh                # faster navigation - See https://github.com/wting/autojump
zplug "plugins/vi-mode", from:oh-my-zsh                 # vim mode in terminal

zplug "zsh-users/zsh-history-substring-search"            #  
zplug "zsh-users/zsh-syntax-highlighting"                 #
zplug "zsh-users/zsh-autosuggestions"                     # suggestions while typing (custom plugin)
zplug "qoomon/zsh-lazyload"                               # Lazy load commands to speed up start up time of zsh.

zplug load --verbose                                      # Should generate the plugins=(...) part.

# plugin settings
unsetopt cdablevars
setopt PROMPT_SUBST
setopt COMPLETE_IN_WORD                                   # complete from both ends of the word
setopt PATH_DIRS                                          # Perform path search even on command names with slashes
setopt AUTO_LIST                                          # Automatically list choices on ambiguous completion. 
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' # case-insensitive matching

VI_MODE_SET_CURSOR=true                                   # Change cursor style in different vim modes.

# Load NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# Exports
export ZSH="/home/emiel/.oh-my-zsh" # path to your oh-my-zsh installation
export VISUAL=""                    # Use vim as default editor (Some programs rely on $VISUAL instead of $EDITOR
export EDITOR="$VISUAL"             # Use vim as default editor
export UPDATE_ZSH_DAYS=7            # auto-update every 7 days.


# Load configs (keep this at the bottom!)
source $ZSH/oh-my-zsh.sh            # load config from oh-my-zsh
source ~/.profile                   # load config from bash_profile


###################
###   ALIASES   ###
###################

alias reload="source ~/.zshrc"
alias c="clear"
alias claer="clear"
