" source ~/.dotfiles/vim/splits.vim
"
" filetype plugin on
" filetype indent on

set nocompatible " This must be first, because it changes other options as a side effect.

let mapleader = ","   " Sets leader key to ','

"General setting
syntax enable
set background=dark
set t_Co=256
set clipboard=unnamed     " Use the same clipboard as system clipboard
set linebreak
set term=screen-256color  "Adds colorsupport inside tmux
set mouse=a               " Enable the mouse in vim.
set wildmenu              " Much nicer tab completion for commands
set scrolloff=5           " Keep 5 lines below and above the cursor 
set autoread              " Reload files changed outside vim
set novisualbell            " No sounds
set gcr=a:blinkon0        " Disable cursor blink
set noswapfile            " No swap files
set nobackup              " No swap files
set nowb                  " No swap files
set nowrap                " No line wrapping

"Tmux
if exists('+termguicolors') " if no tmux set termguicolors
		let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
		let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
		set termguicolors
endif

nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

"Spaces and tabs
set tabstop=2         " 2 space tab
set shiftwidth=2
set softtabstop=2     " 2 space tab
set expandtab         " use spaces for tabs
set smarttab          " insert tabstop number of spaces when the tab key is pressed

"UI Layout
set number          " show line numbers
set showcmd         " show command in bottom bar
set nocursorline    " highlight current line
set lazyredraw      " Don't update screen during macro and script execution.

"Folding
set nofoldenable        " Disable folding by default

"Searching
set ignorecase      " ignore case when searching
set incsearch       " search as characters are entered
set hlsearch        " highlight all matches
set ignorecase        " Searching is not case sensitive

"Disable arrow keys and break the bad habbit :'(
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

"Move normally between wrapped lines
nmap j gj
nmap k gk

"Vim spell
set spellfile=$HOME/.vim-spell-en.utf-8.add " This will be a symlink to the dotfiles version of the spellfile
autocmd FileType markdown setlocal spell    " Spell check markdown
autocmd FileType gitcommit setlocal spell   " Spell check git commit messages
set complete+=kspell                        " For filetypes with spellcheck available, we'll also support auto-complete.

" Don't count acronyms / abbreviations as spelling errors
" (all upper-case letters, at least three characters)
" Also will not count acronym with 's' at the end a spelling error
" Also will not count numbers that are part of this
" Recognizes the following as correct:
au BufNewFile,BufRead syn match AcronymNoSpell '\<\(\u\|\d\)\{3,}s\?\>' contains=@NoSpell
au BufNewFile,BufRead syn match UrlNoSpell '\w\+:\/\/[^[:space:]]\+' contains=@NoSpell

"Vim Plug (pluginmanager)

" Install plugins :PlugInstall
" Remove plugins  :PlugClean
call plug#begin('~/.vim/plugged')

"General
Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}
Plug 'lervag/vimtex'                    " Latex support vim
Plug 'janko-m/vim-test'
Plug 'moll/vim-node'                    " Node support
Plug 'kien/ctrlp.vim'                   " Fuzzy file explorer (literaly open every file)
Plug 'scrooloose/nerdtree'              " Tree viewer
Plug 'Xuyuanp/nerdtree-git-plugin'      " Git status for Nerdtree
Plug 'tpope/vim-fugitive'               " Best git wrapper in the world
Plug 'sjl/vitality.vim'                 " Nicer cursor, tmux interactions
Plug 'docker/docker'                    " Dockerfile code completion
Plug 'nathanaelkane/vim-indent-guides'  " Shows indents
Plug '907th/vim-auto-save'              " Automatically save changes to disk without having to use :w
Plug 'christoomey/vim-tmux-navigator'   " Tmux navigator
Plug 'google/vim-searchindex'           " Show how many times a search pattern occurs in the current buffer.
Plug 'ntpeters/vim-better-whitespace'   " Highlight whitespaces


"Go
Plug 'fatih/vim-go'                                                   " Go support

"Javascript
Plug 'hail2u/vim-css3-syntax'                                         " CSS syntax
Plug 'ap/vim-css-color'                                               " Shows colors
Plug 'styled-components/vim-styled-components', { 'branch': 'main' }  " Styled-components support
Plug 'joegesualdo/jsdoc.vim'                                          " JSDoc support
Plug 'yuezk/vim-js'                                                   " Syntax highlighting Javascript
Plug 'maxmellon/vim-jsx-pretty'                                       " React Syntax Highlighting


"Plugins for Markdown
Plug 'godlygeek/tabular'                " Line up text! Needed by Vim markdown.
Plug 'plasticboy/vim-markdown'          " Markdown support

"Theme
Plug 'bling/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'dracula/vim',{'as':'dracula'}

call plug#end()

" Vimtex
let g:vimtex_complete_img_use_tail = 1
let g:vimtex_fold_enabled = 0
let g:vimtex_format_enabled = 1
let g:vimtex_view_method = 'zathura'
let g:vimtex_indent_ignored_envs = ['document', 'frame']
let g:tex_flavor = 'latex'

"Syntax Highlighting
let g:loaded_matchparen=1
"Javascript
let g:jsx_ext_required = 0                          " Support JSX syntax highlighting in *.js, not just *.jsx.
let g:vim_json_syntax_conceal = 0                   " Disable syntax concealing for json files.

"Vim-go
let g:go_def_mapping_enabled = 0                    " Disable vim-go :GoDef short cut (gd). This is handled by LanguageClient (LC)
let g:go_highlight_build_constraints = 0            " Syntax highlighting
let g:go_highlight_extra_types = 0                  " Syntax highlighting
let g:go_highlight_fields = 0                       " Syntax highlighting
let g:go_highlight_functions = 0                    " Syntax highlighting
let g:go_highlight_methods = 0                      " Syntax highlighting
let g:go_highlight_operators = 0                    " Syntax highlighting
let g:go_highlight_structs = 0                      " Syntax highlighting
let g:go_highlight_types = 0                        " Syntax highlighting

"Vim-airline theme
let g:airline_theme = 'minimalist'
let g:airline_left_sep = ''
let g:airline_left_sep = ''
let g:airline_right_sep = ''
let g:airline_right_sep = ''

"Vim-better-whitespace
let g:better_whitespace_enabled=1
let g:better_whitespace_ctermcolor='lightmagenta'
let g:better_whitespace_guicolor='lightmagenta'
let g:show_spaces_that_precede_tabs=1               " Highlight spaces that appear before or in-between tabs


"Vim-indent-guides
let g:indent_guides_guide_size = 1                  " Size of indent
let g:indent_guides_start_level = 2                 " Starts showing from second level
let g:indent_guides_enable_on_vim_startup = 1       " Enable indent guides on startup

"NERDTree
let NerdTreeShowHidden=1                                                                " Show hidden files by default
let NERDTreeQuitOnOpen = 1                                                              " Automatically close if a file is selected
let NERDTreeMinimalUI = 1                                                               " Cleaner UI
let NERDTreeDirArrows = 1                                                               " Arrows to show that you are opening a folder.
let g:NerdTreeIgnore=['\.git$[[dir]]', 'node_modules$[[dir]]', '\.nyc_output$[[dir]]']  " Ignore node_modules and .git files
autocmd StdinReadPre * let s:std_in=1                                                   " Open NERDTree on startup
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif             " Open NERDTree on startup

"NERDTree keybindings
nmap <leader>v :NERDTreeFind<CR>
nmap <silent> <leader>t :NERDTreeToggle<CR>

"Vim-auto-save
let g:auto_save=1 " Enable AutoSave on startup

"Coc.nvim default settings
set hidden                                                    " If hidden is not set, TextEdit might fail
set cmdheight=2                                               " Better display for messages
set updatetime=300                                            " Smaller updatetime for CursorHold & CursorHoldI
set shortmess+=c                                              " Don't give ins-completion-menu messages.
set signcolumn=yes                                            " Always show signcolumns
autocmd CursorHold * silent call CocActionAsync('highlight')  " Highlight symbol under cursor on CursorHold

"use <tab> for trigger completion and navigate to the next complete item
function! s:check_back_space() abort
    let col = col('.') - 1
      return !col || getline('.')[col - 1]  =~ '\s'
    endfunction

inoremap <silent><expr> <Tab>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<Tab>" :
      \ coc#refresh()

" use <c-space> to trigger completion
inoremap <silent><expr> <c-space> coc#refresh()
" Remap keys for gotos
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)


"Language specific configuration.
au FileType make      set noexpandtab shiftwidth=8 softtabstop=0 " Makefiles must use tabs
au FileType yaml      setl  sw=2 sts=2
au FileType json      syntax match Comment +\/\/.\+$+


colorscheme dracula
