- name: local desktop manager (https://github.com/emielvanseveren)
  hosts: localhost
  connection: local
  roles:
    - { role: geerlingguy.git, become: yes }
    # - base
    #- vim
    - zsh

# - name: servers
