

# General settings
set -s escape-time 10           # faster command sequences
set -sg repeat-time 600         # increase repeat timeout
set -s focus-events on
set -g history-limit 5000       # boost history

bind r source-file ~/.tmux.conf \; display '~/.tmux.conf sourced'


# Display settings
set -g base-index 1         # start windows numbering at 1 (Better for keyboard usage)
setw -g pane-base-index 1   # start pane numbering at 1 (consistent with windows)
set -g set-titles on        # set terminal title
set -g status-interval 10   # redraw status line every 10 seconds
set -g monitor-activity on  # monitor activity
set -g visual-activity off  # disable visual effect
# Navigation
bind - split-window -v      # split current window horizontally
bind _ split-window -h      # split current window vertically
# Mouse management
set -g mouse on 					    	# Enable mouse control (clickable pane,window,resizable pane)

# Colour management
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# Keyboard management
setw -g mode-keys 					  	                          # use vim keybindings in copy mode.
bind-key -T copy-mode-vi v send-keys -X begin-selection 	# setup 'v' begin/end selection as in Vim.
set -sg escape-time 0 				  	                        # Don't wait for an escape sequence after hitting.

# Pane and Window Management
bind c new-window -c "#{pane_current_path}"			# Open new panes and splits in the same working directory.
set-option -g allow-rename off				          # Set the name of the window  intially, but don't let tmux change it.
bind-key h swap-window -t -1					          # <C-B> h swap window.
bind-key l swap-window -t +1					          # <C-B> l swap window.

# Tmux switch pane rebinds (if in vim or not)
bind-key -n C-h if-shell "$is_vim" "send-keys C-h" "select-pane -L"
bind-key -n C-j if-shell "$is_vim" "send-keys C-j" "select-pane -D"
bind-key -n C-k if-shell "$is_vim" "send-keys C-k" "select-pane -U"
bind-key -n C-l if-shell "$is_vim" "send-keys C-l" "select-pane -L"

set -g base-index 1						# start windows at index 1.
set -g pane-base-index 1			# start panes at index 1.
set -g renumber-windows on		# When we add/remove windows, renumber them in sequential order.



######################
### DESIGN CHANGES ###
######################

# Statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'bg=colour18 fg=colour137 dim'
set -g status-left ''
set -g status-right '#[fg=colour233,bg=colour19] %d/%m #[fg=colour233,bg=colour8] %H:%M:%S'
set -g status-right-length 50
set -g status-left-length 20

setw -g window-status-current-style 'fg=colour1 bg=colour19 bold'
setw -g window-status-current-format ' #I#[fg=colour249]:#[fg=colour255]#W#[fg=colour249]#F '
setw -g window-status-style 'fg=colour9 bg=colour18'
setw -g window-status-format ' #I#[fg=colour237]:#[fg=colour250]#W#[fg=colour244]#F '
setw -g window-status-bell-style 'fg=colour255 bg=colour1 bold'	

# Modes 
setw -g clock-mode-colour colour5
setw -g mode-style 'fg=colour1 bg=colour18 bold'

# Panes
set -g pane-border-style 'fg=colour19 bg=colour0'
set -g pane-active-border-style 'bg=colour0 fg=colour9'
