
# Mouse management
  set -g mouse on 						# Enable mouse mode

# Colour management
  set-option -ga terminal-overrides ",xterm-256color:Tc"
  set-option -g default-terminal "screen-256color"

# Keyboard management
  setw -g mode-keys 					  	# use vim keybindings in copy mode.
  bind-key -T copy-mode-vi v send-keys -X begin-selection 	# setup 'v' begin/end selection as in Vim.
  set -sg escape-time 0 				  	# Don't wait for an escape sequence after hitting.
							  	# This also fixes lag on the exit of the vim insert mode.
    
# Pane and Window Management
  bind c new-window -c "#{pane_current_path}"			# Open new panes and splits in the same working directory.
  set-option -g allow-rename off				# Set the name of the window  intially, but don't let tmux change it. 
  bind-key h swap-window -t -1					# <C-B> h swap window.
  bind-key l swap-window -t +1					# <C-B> l swap window.
  set -g base-index 1						# start windows and panes at 1.
  set -g pane-base-index 1					# start windows and panes at 1.
  set -g renumber-windows on					# When we add/remove windows, renumber them in sequential order.
  
  



